# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4473f926f71ee251b1f554d46c56979a5bde1767d8b8d7731d346f58ea8236fba0d45e8ce5921db52a8f28abc85181ffa21624096bdcf34150bde98014df2802

test:
  secret_key_base: 8b1d0bb92de5f4791b2045aed4a26f2d15fc60dd2cc9ab92ecdf2efe2253b9432ee04b617724d4526d71e592334edda732ea493b4f751bb8c04a9a48e14a2e15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
